### ISSUE TITLE
AssertionError: Wrong size for dimension 1: expected 18

### ISSUE THREAD

**Issue by d-t-n** [Goblaski/stylegan2-web-convert#2]
Hi, thank you for the great conversion script!
I tried it out, followed all the recommendations from requirements and legacy pre-processing, even used your examples with NVIDIA models, but got the error message above. Although I got files output with .onnx extension, the model is unusable. Have you ever seen this error?
Would it be possible for you to share your ONNX model for download?
Thanks!

**Comment by Goblaski** [comment]
What model are you looking for to convert? I can convert a public model (e.g. NVIDIA) and make the download available.

**Comment by d-t-n** [comment]
Thank you! And I appreciate the fast response. It can be the one in your example:
https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/stylegan2-cat-config-f.pkl

**Comment by d-t-n** [comment]
Also if you prefer, it can be this one:
!wget -O "network-snapshot-005000.pkl" https://www.dropbox.com/s/jocrpi075qxymwz/network-snapshot-005000.pkl?dl=0

**Comment by Goblaski** [comment]
I fixed the code by now looking at the mapping dimensions dynamically rather than fixed. Tested successfully with the cat model. It should work now. https://github.com/Goblaski/stylegan2-web-convert/commit/f1e0f22d140521f098e606af691ada6545a729b4
