### ISSUE TITLE
Can onnx conversion be implemented for the model of stylegan2? Or do you need the stylegan2-ada project?

### ISSUE THREAD

**Issue by zhanghongyong123456** [Goblaski/stylegan2-web-convert#4]
Can onnx conversion be implemented for the model of stylegan2（https://github.com/yuval-alaluf/restyle-encoder）? Or do only need the stylegan2-ada project（https://github.com/NVlabs/stylegan2-ada-pytorch）?

**Comment by Goblaski** [comment]
I can't open the private github you send. However, using the legacy converter by NVLabs (https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/legacy.py) (Also see the Readme on how to use it) you can convert most older and tensorflow based stylegan2 models.

**Comment by zhanghongyong123456** [comment]
> 
oh，my error
https://github.com/yuval-alaluf/restyle-encoder，this can open this project
i will try yours suggestion
